version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: jobconnect-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./jobconnect-backend
      dockerfile: Dockerfile
    container_name: jobconnect-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - ./jobconnect-backend/.env

  frontend:
    build:
      context: ./jobconnect-frontend
      dockerfile: Dockerfile
    container_name: jobconnect-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    env_file:
      - ./jobconnect-frontend/.env

volumes:
  mysql_data:
