version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: jobconnect-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: imrushier/jobconnect-backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobconnect-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  mysql_data:
